### ISSUE TITLE
Have you considered using composer?

### ISSUE THREAD

**Issue by mgarciaebo** [saleslayer/magento-community-plugin#6]
Hi,

I wonder if you have ever considered to deliver your module using composer.

Installing modules in `app/code` is not a bad practice, but it's way better to manage upgrades and custom patches using a composer installation approach.

We've been mirroring your module to install it this way for a while, however, maintaining multiple custom-made patches along with no composer installation policy makes this process a mess.

If you agree, we can help you with this process, although it's very straightforward in fact. Just don't hesitate to let me know.

Thank you.

**Comment by juliolaguna** [comment]
Hi,

As you say is a good practice a composer integration on third party software, modules or libraries, but is not already set onto our roadmap.
May be in the future our plugins would be integrated with composer/packagist but it's not planned at this moment.

Thank you for your offering,
Kind regards

**Comment by juliolaguna** [comment]
from 2.7.x branch installation of the extension through composer is available.
